# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-05 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logistics_statistic',
        ),
    ]
