# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-05 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0002_delete_logistics_statistic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_All_Yaoqianshu',
            new_name='Products_All_Own',
        ),
    ]
