# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0003_auto_20210605_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_all_own',
            name='cat_name',
            field=models.CharField(max_length=200, null=True, verbose_name='5M分类'),
        ),
    ]
