# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0004_products_all_own_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_all_own',
            name='主图序号',
            field=models.CharField(max_length=10, null=True, verbose_name='主图序号'),
        ),
    ]
