# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0005_products_all_own_主图序号'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_exchange_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('汇率名', models.CharField(max_length=200, null=True, verbose_name='汇率名')),
                ('exchange_rate_0', models.FloatField(null=True, verbose_name='汇率0原始')),
                ('exchange_rate', models.FloatField(null=True, verbose_name='汇率')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
            ],
        ),
        migrations.CreateModel(
            name='key_parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('打包成本', models.FloatField(null=True, verbose_name='打包成本')),
                ('汇损', models.FloatField(null=True, verbose_name='汇损')),
                ('预估买家退货率', models.FloatField(null=True, verbose_name='预估买家退货率')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
            ],
        ),
        migrations.AlterField(
            model_name='products_all_own',
            name='user_collect',
            field=models.CharField(max_length=500, null=True, verbose_name='是否收藏'),
        ),
    ]
