# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-29 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0007_key_parameter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse_show_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.IntegerField(default=0, verbose_name='用户id')),
                ('发货仓库', models.CharField(max_length=200, null=True, verbose_name='发货仓库')),
                ('发货数', models.FloatField(null=True, verbose_name='发货数')),
                ('物流商数', models.FloatField(null=True, verbose_name='物流商数')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
            ],
        ),
    ]
