# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruAndLog', '0010_auto_20210629_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_show_data',
            name='date_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='更新数据时间'),
        ),
    ]
