# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logistics_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('开始日期', models.DateField(null=True, unique=True, verbose_name='保存开始日期')),
                ('结束日期', models.DateField(null=True, verbose_name='保存结束日期')),
                ('可提现', models.CharField(max_length=200, null=True, verbose_name=' 可提现')),
                ('待确认', models.CharField(max_length=200, null=True, verbose_name=' 待确认')),
                ('提现中', models.CharField(max_length=200, null=True, verbose_name=' 提现中')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
            ],
        ),
    ]
