# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-28 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logistics_statistic',
            new_name='funds_5miles_date',
        ),
    ]
