# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0002_auto_20200428_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds_5miles_date',
            name='店铺名',
            field=models.CharField(max_length=200, null=True, verbose_name=' 店铺名'),
        ),
    ]
