# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-29 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0003_funds_5miles_date_店铺名'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessToken_5miles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('store_APIToken', models.CharField(max_length=100, null=True, verbose_name='API密钥')),
            ],
        ),
        migrations.CreateModel(
            name='orders_date_5miles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('order_id', models.IntegerField(null=True, verbose_name='订单id号')),
                ('status', models.CharField(max_length=200, null=True, verbose_name='订单状态')),
                ('status_paid', models.CharField(max_length=200, null=True, verbose_name='付款状态')),
                ('status_shipped', models.CharField(max_length=200, null=True, verbose_name='运输状态')),
                ('status_refunded', models.CharField(max_length=200, null=True, verbose_name='退货状态')),
                ('carrier', models.CharField(max_length=200, null=True, verbose_name='运输公司')),
                ('tracking_number', models.CharField(max_length=200, null=True, verbose_name='物流单号')),
                ('fulfillment_partner', models.CharField(max_length=200, null=True, verbose_name='合作伙伴')),
                ('product_name', models.CharField(max_length=1000, null=True, verbose_name='产品名字')),
                ('product_identifier', models.CharField(max_length=200, null=True, verbose_name='产品标识')),
                ('product_internal_id', models.IntegerField(null=True, verbose_name='产品ID')),
                ('variation_identifier', models.CharField(max_length=200, null=True, verbose_name='变种产品标识')),
                ('variation_internal_id', models.IntegerField(null=True, verbose_name='变种产品ID')),
                ('customer_id', models.IntegerField(null=True, verbose_name='客户ID')),
                ('customer_name', models.CharField(max_length=200, null=True, verbose_name='客户姓名')),
                ('address1', models.CharField(max_length=200, null=True, verbose_name='地址1')),
                ('address2', models.CharField(max_length=200, null=True, verbose_name='地址2')),
                ('city', models.CharField(max_length=200, null=True, verbose_name='城市')),
                ('state', models.CharField(max_length=200, null=True, verbose_name='州')),
                ('postal_code', models.CharField(max_length=200, null=True, verbose_name='邮政编码')),
                ('country', models.CharField(max_length=200, null=True, verbose_name='国家')),
                ('available_refunds_buyer_fee', models.FloatField(null=True, verbose_name='买家可用金额')),
                ('refund_amount', models.FloatField(null=True, verbose_name='退款金额')),
                ('disbursement_amount', models.CharField(max_length=200, null=True, verbose_name='到手价')),
                ('seller_fees_amount', models.FloatField(null=True, verbose_name='卖家支付金额')),
                ('seller_fees_type_sfb', models.CharField(max_length=200, null=True, verbose_name='SFB花费')),
                ('seller_fees_type_buy_nows', models.CharField(max_length=200, null=True, verbose_name='一口价')),
                ('seller_fees_type_buy_nows_price', models.CharField(max_length=200, null=True, verbose_name='一口价价格')),
                ('seller_fees_amount_sfb', models.FloatField(null=True, verbose_name='SFB费用')),
                ('seller_fees_type_com', models.CharField(max_length=200, null=True, verbose_name='佣金')),
                ('seller_fees_amount_com', models.FloatField(null=True, verbose_name='佣金费用')),
                ('seller_fees_type_pro', models.CharField(max_length=200, null=True, verbose_name='手续费')),
                ('seller_fees_amount_pro', models.FloatField(null=True, verbose_name='手续费费用')),
                ('upsells_type_description1', models.CharField(max_length=200, null=True, verbose_name='追销类型1')),
                ('upsells_amount1', models.CharField(max_length=200, null=True, verbose_name='追销类型1费用')),
                ('upsells_description1', models.CharField(max_length=500, null=True, verbose_name='追销类型1描述')),
                ('upsells_type_description2', models.CharField(max_length=200, null=True, verbose_name='追销类型2')),
                ('upsells_amount2', models.CharField(max_length=200, null=True, verbose_name='追销类型2费用')),
                ('upsells_description2', models.CharField(max_length=500, null=True, verbose_name='追销类型2描述')),
                ('refunded_at', models.DateTimeField(null=True, verbose_name='退货时间')),
                ('paid_at', models.DateTimeField(null=True, verbose_name='付款时间')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('canceled_at', models.DateTimeField(null=True, verbose_name='取消订单时间')),
                ('refunded_at_own', models.DateTimeField(null=True, verbose_name='自己退货时间')),
                ('refunded_at_buyer', models.DateTimeField(null=True, verbose_name='买家退货时间')),
                ('refund_amount_own', models.FloatField(null=True, verbose_name='自己退款金额')),
                ('refund_amount_buyer', models.FloatField(null=True, verbose_name='自己退款金额')),
                ('canceled_refund_amount', models.FloatField(null=True, verbose_name='canceled_退款金额')),
                ('canceled_disbursement_amount', models.CharField(max_length=200, null=True, verbose_name='canceled_支付金额')),
                ('canceled_seller_fees_amount', models.FloatField(null=True, verbose_name='canceled_卖家支付金额')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
                ('product_quantity', models.IntegerField(null=True, verbose_name='订单数量')),
                ('data_time_created_at', models.DateField(max_length=30, null=True, verbose_name='创建订单数据生成日期')),
                ('data_time_paid_at', models.DateField(max_length=30, null=True, verbose_name='付款订单数据生成日期')),
                ('hours_time_created_at', models.CharField(max_length=200, null=True, verbose_name='创建订单数据生成时间段')),
                ('SKU_price', models.FloatField(max_length=200, null=True, verbose_name='单价')),
                ('SKU_parts_price', models.FloatField(max_length=200, null=True, verbose_name='配件单价')),
                ('SKU_freight', models.FloatField(max_length=200, null=True, verbose_name='单个运费')),
                ('SKU_parts_freight', models.FloatField(max_length=200, null=True, verbose_name='配件运费')),
                ('SKU_buy_one_freight', models.FloatField(max_length=200, null=True, verbose_name='买一得一运费')),
            ],
        ),
    ]
