# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-15 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0004_apiaccesstoken_5miles_orders_date_5miles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='refund_amount_buyer',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='refund_amount_own',
        ),
    ]
