# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0006_store_cookie_5miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现10',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现10'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现2',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现2'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现3',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现3'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现4',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现4'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现5',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现5'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现6',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现6'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现7',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现7'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现8',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现8'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='可提现9',
            field=models.CharField(max_length=200, null=True, verbose_name=' 可提现9'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认10',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认10'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认2',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认2'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认3',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认3'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认4',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认4'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认5',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认5'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认6',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认6'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认7',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认7'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认8',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认8'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='待确认9',
            field=models.CharField(max_length=200, null=True, verbose_name=' 待确认9'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中10',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中10'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中2',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中2'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中3',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中3'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中4',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中4'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中5',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中5'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中6',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中6'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中7',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中7'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中8',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中8'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='提现中9',
            field=models.CharField(max_length=200, null=True, verbose_name=' 提现中9'),
        ),
    ]
