# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0007_auto_20200612_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_5miles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('products_id', models.IntegerField(null=True, verbose_name='商品ID')),
                ('goods_no', models.CharField(max_length=200, null=True, verbose_name='商品编号')),
                ('cat_id', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('cat_name', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('original_sale_price', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('start_price', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('purchase_price', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('reserve_price', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('shipping_fee', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('cost_price', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='标题')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('main_image_url', models.CharField(max_length=200, null=True, verbose_name='主图')),
                ('weight', models.CharField(max_length=200, null=True, verbose_name='重量')),
                ('min_delivery_days', models.CharField(max_length=200, null=True, verbose_name='最小处理日期')),
                ('max_delivery_days', models.CharField(max_length=200, null=True, verbose_name='最大处理日期')),
                ('delivery_address', models.CharField(max_length=200, null=True, verbose_name='发货地址')),
                ('image_set', models.CharField(max_length=4000, null=True, verbose_name='图片详情')),
                ('sku_set', models.CharField(max_length=4000, null=True, verbose_name='变种详情')),
                ('detail_image_set', models.CharField(max_length=4000, null=True, verbose_name='图片描述详情')),
                ('user_collect', models.CharField(max_length=15, null=True, verbose_name='是否收藏')),
                ('user_collect_reason', models.CharField(max_length=500, null=True, verbose_name='收藏理由')),
                ('colloct_at', models.DateTimeField(null=True, verbose_name='收藏时间')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='available_refunds_buyer_fee',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='canceled_disbursement_amount',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='canceled_refund_amount',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='canceled_seller_fees_amount',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='data_time_created_at',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='data_time_paid_at',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='disbursement_amount',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='hours_time_created_at',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='product_identifier',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='product_internal_id',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='refunded_at_buyer',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='refunded_at_own',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_amount',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_amount_com',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_amount_pro',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_amount_sfb',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_type_buy_nows',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_type_buy_nows_price',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_type_com',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_type_pro',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='seller_fees_type_sfb',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='status_paid',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='status_refunded',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='status_shipped',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='upsells_amount1',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='upsells_amount2',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='upsells_description1',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='upsells_description2',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='upsells_type_description1',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='upsells_type_description2',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='variation_identifier',
        ),
        migrations.RemoveField(
            model_name='orders_date_5miles',
            name='variation_internal_id',
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='amount',
            field=models.FloatField(null=True, verbose_name='成交金额'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='buyer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='买家名称'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='item_lines',
            field=models.CharField(max_length=5000, null=True, verbose_name='订单信息'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='orders_id',
            field=models.CharField(max_length=500, null=True, verbose_name='订单id'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='seq_no',
            field=models.CharField(max_length=200, null=True, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='ship_list',
            field=models.CharField(max_length=5000, null=True, verbose_name='物流信息'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='shipping_address',
            field=models.CharField(max_length=5000, null=True, verbose_name='发货地址'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='shipping_fee',
            field=models.FloatField(null=True, verbose_name='运费金额'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='total_amount',
            field=models.FloatField(null=True, verbose_name='总金额'),
        ),
        migrations.AlterField(
            model_name='orders_date_5miles',
            name='created_at',
            field=models.CharField(max_length=200, null=True, verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='orders_date_5miles',
            name='paid_at',
            field=models.CharField(max_length=200, null=True, verbose_name='订单付款时间'),
        ),
        migrations.AlterField(
            model_name='orders_date_5miles',
            name='state',
            field=models.CharField(max_length=200, null=True, verbose_name='订单状态'),
        ),
    ]
