# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0010_auto_20200613_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_date_5miles',
            name='approved_at',
            field=models.CharField(max_length=100, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='approved_at_data',
            field=models.DateField(null=True, verbose_name='确认日期'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='created_at_data',
            field=models.DateField(null=True, verbose_name='创建日期'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='paid_at_data',
            field=models.DateField(null=True, verbose_name='付款日期'),
        ),
    ]
