# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0011_auto_20200614_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_date_5miles',
            name='seq_no',
            field=models.CharField(max_length=200, null=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='cat_id',
            field=models.CharField(max_length=200, null=True, verbose_name='分类号'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='cat_name',
            field=models.CharField(max_length=200, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='cost_price',
            field=models.CharField(max_length=200, null=True, verbose_name='成本价格'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='original_sale_price',
            field=models.CharField(max_length=200, null=True, verbose_name='原价格'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='purchase_price',
            field=models.CharField(max_length=200, null=True, verbose_name='购买价格'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='reserve_price',
            field=models.CharField(max_length=200, null=True, verbose_name='保留价格'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='shipping_fee',
            field=models.CharField(max_length=200, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='products_5miles',
            name='start_price',
            field=models.CharField(max_length=200, null=True, verbose_name='起拍价'),
        ),
    ]
