# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('five_miles_app', '0012_auto_20200622_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='store_cookie_5miles',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现10',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现2',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现3',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现4',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现5',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现6',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现7',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现8',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='可提现9',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='开始日期',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认10',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认2',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认3',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认4',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认5',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认6',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认7',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认8',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='待确认9',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中10',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中2',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中3',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中4',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中5',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中6',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中7',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中8',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='提现中9',
        ),
        migrations.RemoveField(
            model_name='funds_5miles_date',
            name='结束日期',
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='IP_address',
            field=models.CharField(max_length=100, null=True, verbose_name='店铺IP地址和端口'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='IP_address_status',
            field=models.IntegerField(default=0, verbose_name='店铺IP地址和端口_状态'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='USER_ID',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='beizhu',
            field=models.CharField(max_length=10000, null=True, verbose_name='店铺详细备注'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='created_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='save_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='seller_id',
            field=models.CharField(max_length=50, null=True, verbose_name='卖家ID'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='store_APIToken_status',
            field=models.IntegerField(default=0, verbose_name='API密钥_状态'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='store_cookie',
            field=models.CharField(max_length=10000, null=True, verbose_name='店铺cookie'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='store_cookie_status',
            field=models.IntegerField(default=0, verbose_name='店铺cookie_状态'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='apiaccesstoken_5miles',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='Time_Date',
            field=models.DateField(max_length=30, null=True, verbose_name='数据生成日期'),
        ),
        migrations.AddField(
            model_name='funds_5miles_date',
            name='USER_ID',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='orders_date_5miles',
            name='USER_ID',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='products_5miles',
            name='USER_ID',
            field=models.IntegerField(default=0, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='apiaccesstoken_5miles',
            name='store_name',
            field=models.CharField(max_length=50, null=True, verbose_name='店铺名称'),
        ),
    ]
