# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-18 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_products_note',
        ),
        migrations.DeleteModel(
            name='APIAccessToken',
        ),
        migrations.DeleteModel(
            name='buynows_oders',
        ),
        migrations.DeleteModel(
            name='buynows_statistics',
        ),
        migrations.DeleteModel(
            name='closing_buyer',
        ),
        migrations.DeleteModel(
            name='CN_seller_name',
        ),
        migrations.DeleteModel(
            name='Count_logo',
        ),
        migrations.DeleteModel(
            name='Data_TopData',
        ),
        migrations.DeleteModel(
            name='Founds',
        ),
        migrations.DeleteModel(
            name='Founds_analysis',
        ),
        migrations.DeleteModel(
            name='IP_library',
        ),
        migrations.DeleteModel(
            name='logistics_statistic',
        ),
        migrations.DeleteModel(
            name='own_product_edit',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Performance_hours_time',
        ),
        migrations.DeleteModel(
            name='Performance_yesterday',
        ),
        migrations.DeleteModel(
            name='Price_Freight',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Products_All_Yaoqianshu',
        ),
        migrations.DeleteModel(
            name='Refresh_bargaining_data',
        ),
        migrations.DeleteModel(
            name='StoreSellData',
        ),
        migrations.DeleteModel(
            name='Table_Product_TOP',
        ),
        migrations.DeleteModel(
            name='Table_Sales_amounts',
        ),
        migrations.DeleteModel(
            name='Table_Seller_TOP',
        ),
        migrations.DeleteModel(
            name='The_taxonomy_amount',
        ),
        migrations.DeleteModel(
            name='TODO',
        ),
        migrations.DeleteModel(
            name='TopData',
        ),
    ]
