# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20210318_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=30, null=True, verbose_name='注册手机号'),
        ),
        migrations.AddField(
            model_name='user',
            name='checks',
            field=models.CharField(max_length=30, null=True, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='head_portraits',
            field=models.CharField(max_length=300, null=True, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='limits',
            field=models.CharField(max_length=30, null=True, verbose_name='权限等级'),
        ),
        migrations.AddField(
            model_name='user',
            name='mailbox',
            field=models.CharField(max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=30, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.CharField(max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True, verbose_name='用户名'),
        ),
    ]
