# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20210323_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(default='', max_length=30, verbose_name='注册手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='checks',
            field=models.CharField(default='', max_length=30, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='limits',
            field=models.CharField(default='', max_length=30, verbose_name='权限等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=30, verbose_name='登录密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='用户名'),
        ),
    ]
