# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20210323_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_portraits',
            field=models.CharField(default='', max_length=300, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mailbox',
            field=models.CharField(default='', max_length=100, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=30, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='remarks',
            field=models.CharField(default='', max_length=500, verbose_name='备注'),
        ),
    ]
