# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-10 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20210325_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='USER_ID',
        ),
    ]
