# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-12 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_auto_20210410_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='limits',
            new_name='PRIVILEGE',
        ),
    ]
