# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-04-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_auto_20210412_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_page_name',
            name='page_name',
            field=models.CharField(max_length=300, verbose_name='网页名'),
        ),
    ]
