# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-05 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20210429_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='USER_ID',
            field=models.IntegerField(verbose_name='用户id'),
        ),
    ]
