# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-11-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_functions_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_topdata',
            name='action_price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9, verbose_name='拍卖成交价'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='activated_at',
            field=models.DateTimeField(null=True, verbose_name='订单激活日期'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='bid_order_count',
            field=models.IntegerField(default=0, null=True, verbose_name='拍卖数'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='buy_now_order_count',
            field=models.IntegerField(default=0, null=True, verbose_name='一口价订单数'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='buy_now_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='一口价比例'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='buy_now_shipping_price',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=9, null=True, verbose_name='一口价含运费'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='cn_seller_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='cn_user_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='卖家备注'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='combined_order_count',
            field=models.IntegerField(default=0, null=True, verbose_name='合单数'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='combined_order_rate',
            field=models.IntegerField(default=0, null=True, verbose_name='合单率'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='hammer_order_count',
            field=models.IntegerField(null=True, verbose_name='成交数'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='hammer_order_rate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='成交率'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='hammer_price',
            field=models.IntegerField(default=0, null=True, verbose_name='成交价'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='image_urls',
            field=models.TextField(blank=True, null=True, verbose_name='图片列表'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='module_groupings',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='V2分类'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='order_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='product_video_url',
            field=models.TextField(null=True, verbose_name='视频链接'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='profits',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='退款率'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='purchase_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='采购链接'),
        ),
        migrations.AddField(
            model_name='data_topdata',
            name='site_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='本站ID'),
        ),
    ]
