# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-05 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tophatter_app', '0002_auto_20210515_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logistics_statistic',
        ),
        migrations.DeleteModel(
            name='Products_All_Yaoqianshu',
        ),
    ]
