# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tophatter_app', '0003_auto_20210605_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='logistics_statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAR_DATE', models.DateField(null=True, unique=True, verbose_name='保存开始日期')),
                ('END_DATE', models.DateField(null=True, verbose_name='保存结束日期')),
                ('美国_每克_普货', models.CharField(max_length=200, null=True, verbose_name='美国_每克_普货')),
                ('美国_每克_带电', models.CharField(max_length=200, null=True, verbose_name='美国_每克_带电')),
                ('美国_每克_特货', models.CharField(max_length=200, null=True, verbose_name='美国_每克_特货')),
                ('美国_挂号_普货', models.CharField(max_length=200, null=True, verbose_name='美国_挂号_普货')),
                ('美国_挂号_带电', models.CharField(max_length=200, null=True, verbose_name='美国_挂号_带电')),
                ('美国_挂号_特货', models.CharField(max_length=200, null=True, verbose_name='美国_挂号_特货')),
                ('美国_销售比', models.CharField(max_length=200, null=True, verbose_name='美国_销售比 =')),
                ('美国_折扣_普货', models.CharField(max_length=200, null=True, verbose_name='美国_折扣_普货')),
                ('美国_折扣_带电', models.CharField(max_length=200, null=True, verbose_name='美国_折扣_带电')),
                ('美国_折扣_特货', models.CharField(max_length=200, null=True, verbose_name='美国_折扣_特货')),
                ('英国_每克_普货', models.CharField(max_length=200, null=True, verbose_name=' 英国_每克_普货')),
                ('英国_每克_带电', models.CharField(max_length=200, null=True, verbose_name=' 英国_每克_带电')),
                ('英国_每克_特货', models.CharField(max_length=200, null=True, verbose_name=' 英国_每克_特货')),
                ('英国_挂号_普货', models.CharField(max_length=200, null=True, verbose_name=' 英国_挂号_普货')),
                ('英国_挂号_带电', models.CharField(max_length=200, null=True, verbose_name=' 英国_挂号_带电')),
                ('英国_挂号_特货', models.CharField(max_length=200, null=True, verbose_name=' 英国_挂号_特货')),
                ('英国_销售比', models.CharField(max_length=200, null=True, verbose_name=' 英国_销售比')),
                ('英国_折扣_普货', models.CharField(max_length=200, null=True, verbose_name=' 英国_折扣_普货')),
                ('英国_折扣_带电', models.CharField(max_length=200, null=True, verbose_name=' 英国_折扣_带电')),
                ('英国_折扣_特货', models.CharField(max_length=200, null=True, verbose_name=' 英国_折扣_特货')),
                ('加拿_每克_普货', models.CharField(max_length=200, null=True, verbose_name=' 加拿_每克_普货')),
                ('加拿_每克_带电', models.CharField(max_length=200, null=True, verbose_name=' 加拿_每克_带电')),
                ('加拿_每克_特货', models.CharField(max_length=200, null=True, verbose_name=' 加拿_每克_特货')),
                ('加拿_挂号_普货', models.CharField(max_length=200, null=True, verbose_name=' 加拿_挂号_普货')),
                ('加拿_挂号_带电', models.CharField(max_length=200, null=True, verbose_name=' 加拿_挂号_带电')),
                ('加拿_挂号_特货', models.CharField(max_length=200, null=True, verbose_name=' 加拿_挂号_特货')),
                ('加拿_销售比', models.CharField(max_length=200, null=True, verbose_name=' 加拿_销售比')),
                ('加拿_折扣_普货', models.CharField(max_length=200, null=True, verbose_name=' 加拿_折扣_普货')),
                ('加拿_折扣_带电', models.CharField(max_length=200, null=True, verbose_name=' 加拿_折扣_带电')),
                ('加拿_折扣_特货', models.CharField(max_length=200, null=True, verbose_name=' 加拿_折扣_特货')),
                ('澳大_每克_普货', models.CharField(max_length=200, null=True, verbose_name=' 澳大_每克_普货')),
                ('澳大_每克_带电', models.CharField(max_length=200, null=True, verbose_name=' 澳大_每克_带电')),
                ('澳大_每克_特货', models.CharField(max_length=200, null=True, verbose_name=' 澳大_每克_特货')),
                ('澳大_挂号_普货', models.CharField(max_length=200, null=True, verbose_name=' 澳大_挂号_普货')),
                ('澳大_挂号_带电', models.CharField(max_length=200, null=True, verbose_name=' 澳大_挂号_带电')),
                ('澳大_挂号_特货', models.CharField(max_length=200, null=True, verbose_name=' 澳大_挂号_特货')),
                ('澳大_销售比', models.CharField(max_length=200, null=True, verbose_name=' 澳大_销售比')),
                ('澳大_折扣_普货', models.CharField(max_length=200, null=True, verbose_name=' 澳大_折扣_普货')),
                ('澳大_折扣_带电', models.CharField(max_length=200, null=True, verbose_name=' 澳大_折扣_带电')),
                ('澳大_折扣_特货', models.CharField(max_length=200, null=True, verbose_name=' 澳大_折扣_特货')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
                ('USER_ID', models.IntegerField(default=0, verbose_name='用户id')),
            ],
        ),
    ]
