# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tophatter_app', '0004_logistics_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('type', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='店铺名称')),
                ('daily_budget', models.FloatField(null=True, verbose_name='daily_budget')),
                ('bid_amount', models.FloatField(null=True, verbose_name='bid_amount')),
                ('daily_budget_per_product', models.FloatField(null=True, verbose_name='daily_budget_per_product')),
                ('lifetime_budget', models.FloatField(null=True, verbose_name='lifetime_budget')),
                ('lifetime_budget_per_product', models.FloatField(null=True, verbose_name='lifetime_budget_per_product')),
                ('hourly_schedule', models.FloatField(null=True, verbose_name='hourly_schedule')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新数据时间')),
                ('save_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建数据时间')),
                ('USER_ID', models.IntegerField(default=0, verbose_name='用户id')),
            ],
        ),
    ]
