# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tophatter_app', '0006_auto_20210630_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign_list',
            name='hourly_schedule',
            field=models.CharField(max_length=100, null=True, verbose_name='hourly_schedule'),
        ),
        migrations.AlterField(
            model_name='logistics_statistic',
            name='STAR_DATE',
            field=models.DateField(null=True, verbose_name='保存开始日期'),
        ),
    ]
